[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bonding_curve = "D4v6TSysjvwLn5nWo3XjcCoQLtwcrFZaRKn1RZ9aXpFM"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = " ~/.config/solana/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
